// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace IndexLessNamespace {
	export interface IIndexLess {
		error: string
		'error-active': string
		formItem: string
		imgDiv: string
		item: string
		loginBox: string
		msgBtn: string
		registerBtn: string
	}
}

declare const IndexLessModule: IndexLessNamespace.IIndexLess & {
	/** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
	locals: IndexLessNamespace.IIndexLess
}

export = IndexLessModule
